#!/usr/bin/bash

# A script to deploy a certificate generated by acme.sh to a local UNMS/USIP instance.

# Global vairables (either set here by uncommenting or in the environment before calling this script) 

#export DEPLOY_UNMS_DIR="/home/unms/data/cert" # defaults to /home/unms/data/cert
#export DEPLOY_UNMS_CERTNAME="custom.crt" # defaults to custom.crt
#export DEPLOY_UNMS_KEYNAME="custom.key" # defaults to custom.key
#export DEPLOY_UNMS_CA="ca.crt" # defaults to ca.crt
#export DEPLOY_UNMS_FULLCHAIN="fullchain.crt" # defaults to fullchain.crt
#export DEPLOY_UNMS_CMD="/home/unms/app/unms-cli refresh-certificate" # defaults to /home/unms/app/unms-cli refresh-certificate


########  Do not edit below this line #####################

#domain keyfile certfile cafile fullchain
unms_deploy() {
  _cdomain="$1"
  _ckey="$2"
  _ccert="$3"
  _cca="$4"
  _cfullchain="$5"

  _debug _cdomain "$_cdomain"
  _debug _ckey "$_ckey"
  _debug _ccert "$_ccert"
  _debug _cca "$_cca"
  _debug _cfullchain "$_cfullchain"

  #Setting defaults
  _getdeployconf DEPLOY_UNMS_DIR
  if [ -z "$DEPLOY_UNMS_DIR" ]; then
    _target_directory="/home/unms/data/cert"
  else
    _target_directory="$DEPLOY_UNMS_DIR"
    _savedeployconf DEPLOY_UNMS_DIR "$DEPLOY_UNMS_DIR"
  fi
  _debug2 DEPLOY_UNMS_DIR "$_target_directory"

  _getdeployconf DEPLOY_UNMS_CERTNAME
  if [ -z "$DEPLOY_UNMS_CERTNAME" ]; then
    _target_certificate="custom.crt"
  else
    _target_certificate="$DEPLOY_UNMS_CERTNAME"
    _savedeployconf DEPLOY_UNMS_CERTNAME "$DEPLOY_UNMS_CERTNAME"
  fi
  _debug2 DEPLOY_UNMS_CERTNAME "$_target_certificate"

  _getdeployconf DEPLOY_UNMS_KEYNAME
  if [ -z "$DEPLOY_UNMS_KEYNAME" ]; then
    _target_key="custom.key"
  else
    _target_key="$DEPLOY_UNMS_KEYNAME"
    _savedeployconf DEPLOY_UNMS_KEYNAME "$DEPLOY_UNMS_KEYNAME"
  fi
  _debug2 DEPLOY_UNMS_CERTNAME "$_target_key"

  _getdeployconf DEPLOY_UNMS_CA
  if [ -z "$DEPLOY_UNMS_CA" ]; then
    _target_ca="ca.crt"
  else
    _target_ca="$DEPLOY_UNMS_CA"
    _savedeployconf DEPLOY_UNMS_CA "$DEPLOY_UNMS_CA"
  fi
  _debug2 DEPLOY_UNMS_CA "$_target_ca"

  _getdeployconf DEPLOY_UNMS_FULLCHAIN
  if [ -z "$DEPLOY_UNMS_FULLCHAIN" ]; then
    _target_fullchain="fullchain.crt"
  else
    _target_fullchain="$DEPLOY_UNMS_FULLCHAIN"
    _savedeployconf DEPLOY_UNMS_FULLCHAIN "$DEPLOY_UNMS_FULLCHAIN"
  fi
  _debug2 DEPLOY_UNMS_FULLCHAIN "$_target_fullchain"

  _getdeployconf DEPLOY_UNMS_CMD
  if [ -z "$DEPLOY_UNMS_CMD" ]; then
    _target_cmd="service unms restart"
  else
    _target_cmd="$DEPLOY_UNMS_CMD"
    _savedeployconf DEPLOY_UNMS_CMD "$DEPLOY_UNMS_CMD"
  fi
  _debug2 DEPLOY_UNMS_CMD "$_target_cmd"


  # copy to overwrite existing certificate
  _info "Copying UNMS certificate files to $_target_directory"
  cp $_ckey $_target_directory/$_target_key
    _err_code="$?"
  if [ $_err_code -ne 0 ]; then
    _err "Error: Failed to copy UNMS private key to $_target_directory/$_target_key"
    return $_err_code
  fi
  cp $_ccert $_target_directory/$_target_certificate
    _err_code="$?"
  if [ $_err_code -ne 0 ]; then
    _err "Error: Failed to copy UNMS public certificate to $_target_directory/$_target_certificate"
    return $_err_code
  fi
  cp $_cca $_target_directory/$_target_ca
   _err_code="$?"
  if [ $_err_code -ne 0 ]; then
    _err  "Error: Failed to copy UNMS CA certificate to $_target_directory/$_target_ca"
    return $_err_code
  fi
  cp $_cfullchain $_target_directory/$_target_fullchain
  _err_code="$?"
  if [ $_err_code -ne 0 ]; then
    _err "Error: Failed to copy UNMS full certificate chain to $_target_directory/$_target_fullchain"
    return $_err_code
  fi
    
  # restart UNMS
  $_target_cmd
  _err_code="$?"
  if [ "$_err_code" != "0" ]; then
    _err "Error code $_err_code returned from restarting UNMS"
  fi

  return $_err_code
  
}
